data:
  data_dir: ./data/raw/original/
  data_dir_paper: ./data/raw/Paper Data/
  data_dir_self: ./data/raw/original/
  data_name: original_datasetA
  data_source: self
  dataset_a_name: original_datasetA
  dataset_b_name: original_datasetB
  dataset_type: channel
  interpolation: rbf
  normalisation: minmax
  normalise_before_interp: false
  normalise_target: true
  num_pilots: 48
  num_workers: 0
  preprocessed_dir: ./data/preprocessed/
  snr: 20
  test_split: 0.15
  validation_split: 0.15
evaluation:
  metrics:
  - nmse
  - psnr
  - mse
  - ssim
  save_results_dir: ./standard_training/checkpoints/srcnn/evaluations/
experiment_name: srcnn
framework:
  seed: 42
hardware:
  device: auto
  use_amp: true
logging:
  checkpoint_dir: ./standard_training/checkpoints/srcnn/
model:
  name: srcnn
  params: {}
  pretrained_path: null
training:
  batch_size: 64
  betas:
  - 0.9
  - 0.999
  early_stopping_patience: 15
  epochs: 100
  eps: 1e-8
  learning_rate: 8.196878933111657e-05
  loss_function: huber
  optimiser: adam
  scheduler: true
  scheduler_factor: 0.1
  scheduler_min_lr: 1e-6
  scheduler_patience: 5
  scheduler_type: ReduceLROnPlateau
  weight_decay: 0.0001
