# Dataset B - High multipath, challenging SNR environment
antenna_distance: 100           # Meters
tx_gain: 10                     # dBi
rx_gain: 10                     # dBi
snr: [0, 10]                    # dB (poor to moderate conditions)
num_clusters: [8, 20]           # Integer number of cluster locations (dense urban)
speed: [5, 15]                  # m/s (vehicular speeds)
subcarrier_spacing: 60000       # Hz
use_aggregate_scattering: true  # Whether to use H_{ij} term for system model
blocks: 4                       # Number of 14-symbol blocks to generate
output_dir: "./data/raw/ray_tracing/dataset_b" # Output directory for this dataset (change depending on which dataset is being generated)
