# Dataset A - Low multipath, good SNR environment

# ---- System Parameters ----
blocks: 4                       # Number of OFDM blocks per sample
carrier_frequency: 2490         # Carrier frequency (MHz)
subcarrier_spacing: 60000       # Subcarrier spacing (Hz)

# ---- Environment Type and Dimensions ----
environment_type: "RMa"                 # Which 3GPP preset to use as base (RMa = Rural Macrocell)
environment_dimensions: [1000, 1000, 310]  # Dimensions of the environment (x, y, z) - not in presets

# ---- Parameter Overrides ----
# Override these specific parameters from the RMa preset
num_clusters: [1, 5]               # Deliberately reduced from [8, 11] in RMa preset
cluster_density: 1.0               # Increased from 0.4 in RMa preset
cluster_radius: 6                  # Reduced from 35 in RMa preset
# cluster_height_range: 1000        
rms_delay_spread_ns: 250           # Modified from 129 in RMa preset
use_aggregate_scattering: true     # Modified from false in RMa preset
far_field_margin: 6e-2             # Far field region of 6cm

# ---- Custom Movement Parameters ----
scatterer_movement_type: "linear"     # Movement model to use

# ---- Flocking Movement Parameters ----
cluster_movement_params:
  flock_movement_direction: [1, 0, 0] # Direction vector [x, y, z]

# ---- Output Settings ----
output_dir: "./data/raw/ray_tracing/dataset_a" # Output directory for this dataset