# Dataset Mixed - Wide range of channel conditions
antenna_distance: 100  # Meters
tx_gain: 10  # dBi
rx_gain: 10  # dBi
snr: [0, 30]  # dB (very poor to excellent conditions)
num_clusters: [2, 25]  # Integer number of cluster locations (rural to dense urban)
speed: [0.5, 30]  # m/s (stationary to high-speed vehicular)
subcarrier_spacing: 60000  # Hz
use_aggregate_scattering: [true, false]  # Both with and without aggregate scattering
blocks: 4  # Number of 14-symbol blocks to generate
output_dir: "./data/raw/ray_tracing/dataset_mixed" # Output directory for this dataset (change depending on which dataset is being generated)
