blocks: 5                       # Number of OFDM blocks per sample
carrier_frequency: 2490         # Carrier frequency (MHz)
subcarrier_spacing: 60000       # Subcarrier spacing (Hz)
rms_delay_spread_ns: 45   
use_aggregate_scattering: true     
far_field_margin: 6e-2  

environment:
  environment_type: "UMa"             
  environment_dimensions: [200,100,100]
  road_width: 20
  pavement_width: 3.5
  buildings_per_side: 10
  floor_height: 3.0

antennas:
  tx_antenna:
    gain: 15
    target_height: 25.0
  rx_antenna:
    gain: 0
    target_height: 1.5
    movement:
      type: "linear"
      speed: [100,200]
      linear_params:
        direction: [1, 0, 0] 

      forward_back_params:
        direction: [1, 0, 0] 
        distance: 20         

      circular_params:
        center_offset: [10, 0] 
        radius: 1              
        clockwise: true        

      zigzag_params:
        main_direction: [1, 0, 0] 
        leg_length: 10            
        angle_deg: 45             
        num_legs: 6               

clusters:
  num_aerial_clusters_rng:    [2, 4]
  num_ground_clusters_rng:    [5, 12]
  num_scatterers_per_cluster: 50
  movement_type:              "flocking"
  speed_range:                [0,0]
  density:                    0.5
  reflection_amplitude:       null
  
  # Movement-specific parameters for different movement types
  movement_params:
    # Random walk parameters
    random_walk:
      direction_change_prob: 0.4
      max_angle_change: 45  
    
    # Linear movement parameters
    linear:
      direction: [1, 0, 0]
    
    # Flocking movement parameters
    flocking:
      flock_movement_direction: [1, 0, 0]


# Output Settings
output_dir: "./data/raw/ray_tracing/dataset_a" 