# Rural Environment - Low multipath, variable speed, good SNR
antenna_distance: 200            # Meters (larger distances in rural areas)
tx_gain: 10                      # dBi
rx_gain: 10                      # dBi
snr: [15, 25]                    # dB (good conditions)
num_clusters: [1, 4]             # Integer number of cluster locations (sparse scattering)
speed: [0.5, 40]                 # m/s (pedestrian to vehicle speeds)
subcarrier_spacing: 60000        # Hz
use_aggregate_scattering: false  # No aggregate scattering in rural environments
blocks: 4                        # Number of 14-symbol blocks to generate
output_dir: "./data/raw/ray_tracing/rural_environment" # Output directory for this dataset
