# Urban Environment - Dense multipath, variable speed, challenging SNR
antenna_distance: 100           # Meters
tx_gain: 10                     # dBi
rx_gain: 10                     # dBi
snr: [0, 20]                    # dB (variable conditions)
num_clusters: [10, 30]          # Integer number of cluster locations (dense scattering)
speed: [0.5, 20]                # m/s (pedestrian to vehicle speeds)
subcarrier_spacing: 60000       # Hz
use_aggregate_scattering: true  # Use aggregate scattering in urban environments
blocks: 4                       # Number of 14-symbol blocks to generate
output_dir: "./data/raw/ray_tracing/urban_environment" # Output directory for this dataset
