# --- Basic Autoencoder Configuration for Standard Training 2.0 ---
# Description: Configuration for training a basic (non-residual) denoising autoencoder

experiment_name: basic_autoencoder_standard_training_2

framework:
  seed: 42

model:
  name: denoising_autoencoder
  params:
    input_channels: 2

data:
  dataset_type: standard
  data_dir: ./data/raw/ray_tracing/
  preprocessed_dir: ./data/preprocessed/
  data_name: domain_high_snr_med_linear  # Change this to your dataset filename
  snr: 20  # SNR value for noise addition
  validation_split: 0.15
  test_split: 0.15
  
  # Interpolation settings (currently not used by StandardDataset, but kept for potential future use)
  interpolation_method: rbf
  interpolation_kernel: thin_plate_spline
  
  # Training parameters
  num_workers: 0 # Set to 0 for Windows or for simpler debugging
  pin_memory: True
  persistent_workers: False # Set to False if num_workers is 0

training:
  epochs: 100
  batch_size: 64 # Adjusted for consistency, can be tuned
  loss_function: mse
  optimiser: adam
  learning_rate: 1e-4
  weight_decay: 0
  betas: [0.9, 0.999]
  eps: 1e-8

  scheduler:
    type: ReduceLROnPlateau
    params:
      mode: min
      factor: 0.1
      patience: 10
      min_lr: 1e-7
      verbose: True

  early_stopping:
    patience: 20
    min_delta: 0.00001

evaluation:
  metrics: [nmse, psnr, mse, ssim]
  save_results_dir: ./standard_training_2/results/
  save_plot_path: ./standard_training_2/plots/basic_autoencoder_evaluation.png
  plot_examples: 3
  optuna_wandb_num_plots: 3

logging:
  checkpoint_dir: ./standard_training_2/checkpoints/basic_autoencoder/
  wandb_enabled: False

hardware:
  device: auto
  use_amp: True
  compile_model: False 