# --- SRCNN Baseline Configuration ---
experiment_name: srcnn

framework:
  seed: 42

model:
  name: srcnn
  params: {} 
  pretrained_path: C:\Users\Vincenzo_DES\OneDrive - Imperial College London\Year 4\ELEC70017 - Individual Project\Project\standard_training\checkpoints\srcnn\srcnn-20250515_151439\best_model.pth

data:
  dataset_type: standard
  data_dir: ./data/raw/original/ 
  preprocessed_dir: ./data/preprocessed/original/ 
  # data processing parameters
  interpolation: rbf 
  normalisation: minmax                                        # <-- can be zscore / minmax / None 
  normalise_before_interp: False 
  normalise_target: True
  # dataset parameters
  data_name:  original_datasetA  
  dataset_a_name: original_datasetA
  dataset_b_name: original_datasetB
  validation_split: 0.15
  test_split: 0.15
  # training parameters
  num_workers: 0

training:
  epochs: 100
  batch_size: 64
  loss_function: huber  # can use <--- huber / mse / mae
  # huber_delta: 0.5
  optimiser: adam
  learning_rate: 8.196878933111657e-05
  weight_decay: 0.0001
  betas: [0.9, 0.999]
  eps: 1e-8
  # scheduler parameters
  scheduler: True
  scheduler_type: ReduceLROnPlateau
  scheduler_factor: 0.1
  scheduler_patience: 5
  scheduler_min_lr: 1e-6
  early_stopping_patience: 15 #  .inf

evaluation:
  metrics: [nmse, psnr, mse, ssim] 
  save_results_dir: ./standard_training/checkpoints/srcnn/evaluations/

logging:
  checkpoint_dir: ./standard_training/checkpoints/srcnn/

hardware:
  device: auto
  use_amp: True 